### ISSUE TITLE
Loop Ended

### ISSUE THREAD

**Issue by duffxp** [pando85/i3-auto-layout#20]
I'm getting this error:
```
┌─[quintana@debian]─[~]─[20:24:02]
└──╼ $ RUST_LOG=debug i3-auto-layout
DEBUG [i3_auto_layout] Sender loop ended
DEBUG [i3_auto_layout] Receiver loop ended
```
I've downloaded the last file and compiled it on my system, but it just stopped when I tried to create another window.

**Comment by pando85** [comment]
Released v0.3.5 with this fixed.
Thanks for reporting.
