### ISSUE TITLE
Bug? [flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset

### ISSUE THREAD

**Issue by Samueru-sama** [pando85/i3-auto-layout#9]
I get that error when running the released binary. And it also prints this link: https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time

However so far everything works like it should, so I'm not sure if this is even a bug. Sorry for bothering.

**Comment by pando85** [comment]
I released 0.3.3: If you can confirm that it is fixed I will close this issue. 

Thank you very much.

**Comment by Samueru-sama** [comment]
Works now thank you!
